---

- name: Copiar contenido web spoof
  ansible.builtin.copy:
    src: sites.tar
    dest: /tmp/sites.tar

- name: Unarchive sites
  ansible.builtin.unarchive:
    src: /tmp/sites.tar
    dest: /tmp/

- name: Block
  block:
    - name: Stat carpeta
      ansible.builtin.stat:
        path: /var/www/html
      register: carpeta

    - name: Eliminar carpeta
      ansible.builtin.file:
        path: /var/www/html
        state: absent
      when: carpeta.stat.exists

- name: Crear carpeta
  ansible.builtin.file:
    path: /var/www/html
    state: directory
    owner: "{{ owner }}"
    group: "{{ owner }}"
    mode: '0755'

- name: Copy to apache
  ansible.builtin.copy:
    src: "/tmp/sites/{{ web_spoof }}/"
    dest: /var/www/html
    remote_src: true

- name: Cambiar permisos
  ansible.builtin.file:
    path: /var/www/html
    owner: "{{ owner }}"
    group: "{{ owner }}"
    mode: '0777'
    recurse: true


# - name: Ataque arpspoofing
#   arp_dns_spoofing:
#     interface: "{{ interface }}"
#     target: "{{ target }}"
#     gateway: "{{ gateway }}"
#     state: arpspoofing
#   async: 10000000000000000000000
#   poll: 0

# - name: Ataque dnsspoofing
#   arp_dns_spoofing:
#     interface: "{{ interface }}"
#     file: 
#     state: dnsspoofing


...