---

- name: Install apache/httpd
  ansible.builtin.package:
    name: "{{ web_service }}"
    state: present

- name: Levantar servicio
  ansible.builtin.service:
    name: "{{ web_service }}"
    state: started
    enabled: true

- name: Copiar contenido web spoof
  ansible.builtin.copy:
    src: sites.tar
    dest: /tmp/sites.tar

- name: Unarchive sites
  ansible.builtin.unarchive:
    src: /tmp/sites.tar
    dest: /tmp/

- name: Copy to apache
  ansible.builtin.copy:
    src: "/tmp/sites/{{ web_spoof }}/"
    dest: /var/www/html
    remote_src: true

- name: Rename folder
  ansible.builtin.lineinfile:
    


# - name: Ataque arpspoofing
#   arp_dns_spoofing:
#     interface: "{{ interface }}"
#     target: "{{ target }}"
#     gateway: "{{ gateway }}"
#     state: arpspoofing
#   async: 10000000000000000000000
#   poll: 0

# - name: Ataque dnsspoofing
#   arp_dns_spoofing:
#     interface: "{{ interface }}"
#     file: 
#     state: dnsspoofing


...